# Default values for elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metricbeat:
  daemonset:
    hostNetworking: true

logstash:
  enabled: false

  persistence:
    enabled: true

  logstashConfig:
    logstash.yml: |
      http.host: 0.0.0.0
      xpack.monitoring.enabled: false
  logstashPipeline:
    uptime.conf: |
      input { exec { command => "uptime" interval => 30 } }
      output { elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }

  service:
    annotations: {}
    type: ClusterIP
    ports:
      - name: beats
        port: 5044
        protocol: TCP
        targetPort: 5044
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
