# Default values for avalanche-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: mainnet

replicaCount: 1

image:
  name: registry.gitlab.com/thorchain/devops/node-launcher
  tag: "avalanche-daemon-1.12.0"
  hash: a88435d9c13d656d7ca385582ad7a01e72f917a573551ef6d65539a719fb12ad

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9650

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls:
    []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    stagenet: 1Ti
    mainnet: 1Ti
  accessMode: ReadWriteOnce
  # storageClass: "-"
  #
resources:
  limits:
    # cpu: 1
    memory: 12Gi
  requests:
    cpu: 1
    memory: 6Gi

nodeSelector: {}

tolerations: []

affinity: {}

global: {}
