apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethereum-daemon.fullname" . }}-scripts
data:
  probe.sh: |
    #!/bin/sh

    FILE=/root/.probe_last_height

    if [ "$NET" = "testnet" ]; then
      SYNCING=$(geth --ropsten attach --exec eth.syncing) || exit 1
      HEIGHT=$(geth --ropsten attach --exec eth.blockNumber) ||  exit 1
    else
      SYNCING=$(geth attach --exec eth.syncing) || exit 1
      HEIGHT=$(geth attach --exec eth.blockNumber) || exit 1
    fi

    # first time we are syncing from scratch
    if [ "$SYNCING" != "false" ] && [ "$HEIGHT" = "0" ]; then
      exit 0
    fi

    if [ ! -f "$FILE" ]; then
      echo "$HEIGHT" >$FILE
      echo "Not getting new blocks"
      exit 1
    fi

    OLD=$(cat $FILE)
    echo "$HEIGHT" >$FILE
    if [ "$OLD" = "$HEIGHT" ]; then
      echo "Not getting new blocks"
      exit 1
    fi
    exit 0
