apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cardano-daemon.fullname" . }}-scripts
data:
  probe.sh: |
    #!/bin/sh

    set -euo pipefail

    TIP=$(cardano-cli query tip --socket-path /data/node.socket --mainnet) || exit 1
    echo "$TIP"

  init.sh: |
    #!/bin/sh

    set -euo pipefail

    # download genesis if it does not exist
    if [ ! -f /data/config.json ]; then
      cd /data
      wget https://book.world.dev.cardano.org/environments/mainnet/config.json
      wget https://book.world.dev.cardano.org/environments/mainnet/topology.json
      wget https://book.world.dev.cardano.org/environments/mainnet/byron-genesis.json
      wget https://book.world.dev.cardano.org/environments/mainnet/shelley-genesis.json
      wget https://book.world.dev.cardano.org/environments/mainnet/alonzo-genesis.json
      wget https://book.world.dev.cardano.org/environments/mainnet/conway-genesis.json
    fi

    # download snapshot if it does not exist
    if [ ! -f "/data/db/lock" ]; then
      apk add zstd jq 
      wget -c -O - "https://downloads.csnapshots.io/mainnet/$(wget -qO- https://downloads.csnapshots.io/mainnet/mainnet-db-snapshot.json | jq -r .[].file_name)" | zstd -d -c | tar -x -C /data
    fi