apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "midgard.fullname" . }}-config
data:
  entrypoint.sh: |
    #!/bin/sh

    # get ordinal index of stateful set from hostname
    INDEX=${HOSTNAME##*-}
    sed -e "s/HOST_TIMESCALEDB/{{ include "midgard.fullname" . }}-timescaledb-${INDEX}.{{ include "midgard.fullname" . }}-timescaledb/g" /config.json.tpl >/config.json
    /midgard /config.json

  config.json: |
    {
      "listen_port": {{ .Values.service.port }},
      "thorchain": {
        "tendermint_url": "http://{{ include "midgard.thorDaemon" . }}/websocket",
        "thornode_url": "http://{{ .Values.thorApi }}/thorchain",
        "last_chain_backoff": "7s",
        "proxied_whitelisted_endpoints": [
          "inbound_addresses",
          "constants",
          "lastblock",
          "mimir",
          "nodes",
          "queue"
        ]
      },
      "timescale": {
        "host": "HOST_TIMESCALEDB",
        "port": {{ .Values.postgres.port }},
        "user_name": "{{ .Values.postgres.username }}",
        "password": "{{ .Values.postgres.password }}",
        "database": "{{ .Values.postgres.database }}",
        "sslmode": "disable",
        "max_open_conns": 80
      },
      "usdpools": [
        "BNB.BUSD-BD1",
        "BNB.BUSD-BAF",
        "BNB.BUSD-74E",
        "BNB.USDT-DC8",
        "ETH.USDT-0XDAC17F958D2EE523A2206206994597C13D831EC7",
        "ETH.USDC-0XA0B86991C6218B36C1D19D4A2E9EB0CE3606EB48",
        "ETH.USDT-0XA3910454BF2CB59B8B3A401589A3BACC5CA42306",
        "ETH.USDT-0X62E273709DA575835C7F6AEF4A31140CA5B1D190",
        "TERRA.UST"
      ]
    }
