stages:
  - validate

linter:
  image: registry.gitlab.com/thorchain/devops/node-launcher
  stage: validate
  script:
    - ./scripts/lint.sh

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  stage: validate

secret_detection:
  stage: validate

variables:
  SCAN_KUBERNETES_MANIFESTS: "true"
  KUBESEC_HELM_CHARTS_PATH: ./thornode-stack
  KUBESEC_HELM_OPTIONS: --dependency-update
