apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos-daemon.fullname" . }}-scripts
data:    
  check-hardfork.sh: |
    #!/bin/sh
    apk add wget bash
    ./scripts/hardfork-upgrade.sh

  hardfork-upgrade.sh: |
    #!/bin/bash
    HARDFORK_HEIGHT={{ include "cosmos-daemon.hardforkHeight" . }}
    DEPLOYMENT_NAME={{ include "cosmos-daemon.fullname" . }}
    
    wget https://dl.k8s.io/release/v1.22.2/bin/linux/amd64/kubectl -P /usr/bin
    chmod +x /usr/bin/kubectl

    {{ .Values.app }} start --home /opt/cosmos > /opt/cosmos/hardfork.output 2>&1 &
    COSMOS_PID=$!
    echo "Checking for current blockheight with cosmos daemon PID ($COSMOS_PID)"

    sleep 15
    STORE_HEIGHT=$(grep "ABCI Replay Blocks" /opt/cosmos/hardfork.output | cut -d " " -f 9)
    STORE_HEIGHT_INT=$(echo "$STORE_HEIGHT" | cut -d "=" -f 2)
    echo "Found store height: $STORE_HEIGHT_INT, hardfork height: $HARDFORK_HEIGHT"
    
    IMAGE=$(kubectl get deployment $DEPLOYMENT_NAME -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d ":" -f 2)
    echo "Kubernetes image: $IMAGE"

    if [ "$STORE_HEIGHT_INT" = "$HARDFORK_HEIGHT" ] && [ "$IMAGE" = "v4.2.1" ]; then
      echo "Hardfork upgrade block height met. Patching app version..."
    fi

    ps aux | grep "[f]$COSMOS_PID" && kill "$COSMOS_PID"


  init-daemon.sh: |
    #!/bin/sh
    set -ev

    if [ ! -f /opt/cosmos/config/genesis.json ]; then
      /usr/bin/$APP_NAME init thorchain --home /opt/cosmos
      cp /home/genesis.json /opt/cosmos/config/genesis.json
    fi