apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos-daemon.fullname" . }}-scripts
data:
  init-daemon.sh: |
    #!/bin/sh
    set -ev
    
    if [ ! -f /opt/cosmos/config/genesis.json ]; then
      /usr/bin/$APP_NAME init thorchain --home /opt/cosmos
      cp /home/genesis.json /opt/cosmos/config/genesis.json
    fi
    
