apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-daemon.fullname" . }}
  labels:
    {{- include "binance-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{.Values.service.port.p2p}}
      {{ end }}
    - port: {{ .Values.service.port.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{.Values.service.port.rpc}}
      {{ end }}
    - port: {{ .Values.service.port.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{.Values.service.port.prometheus}}
      {{ end }}
  selector:
    {{- include "binance-daemon.selectorLabels" . | nindent 4 }}
