apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-daemon.fullname" . }}-p2p
  labels:
    {{- include "binance-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.p2p.type }}
  ports:
    - port: {{ .Values.service.p2p.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "binance-daemon.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-daemon.fullname" . }}-rpc
  labels:
    {{- include "binance-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rpc.type }}
  ports:
    - port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "binance-daemon.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-daemon.fullname" . }}-prometheus
  labels:
    {{- include "binance-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.prometheus.type }}
  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "binance-daemon.selectorLabels" . | nindent 4 }}
