thor-daemon:
  fullnameOverride: thor-daemon

thor-api:
  fullnameOverride: thor-api

bifrost:
  fullnameOverride: bifrost

midgard:
  fullnameOverride: midgard

binance-daemon:
  fullnameOverride: binance-daemon

bitcoin-daemon:
  enabled: false
  fullnameOverride: bitcoin-daemon

ethereum-daemon:
  enabled: false
  fullnameOverride: ethereum-daemon

bepswap:
  enabled: false
  fullnameOverride: bepswap
