global:
  net: mainnet
  gateway:
    enabled: false
    name: thor-gateway

thor-gateway:
  fullnameOverride: thor-gateway

thor-daemon:
  fullnameOverride: thor-daemon
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer

thor-api:
  fullnameOverride: thor-api
  image:
    pullPolicy: Always

bifrost:
  fullnameOverride: bifrost
  bitcoinDaemon:
    enabled: true
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer

midgard:
  fullnameOverride: midgard
  image:
    pullPolicy: Always

binance-daemon:
  fullnameOverride: binance-daemon

bitcoin-daemon:
  enabled: true
  fullnameOverride: bitcoin-daemon

ethereum-daemon:
  enabled: false
  fullnameOverride: ethereum-daemon

bepswap:
  enabled: false
  fullnameOverride: bepswap
