global:
  net: mainnet
  gateway:
    enabled: true
    name: thor-gateway

thor-gateway:
  fullnameOverride: thor-gateway

thor-daemon:
  fullnameOverride: thor-daemon
  image:
    pullPolicy: Always

thor-api:
  fullnameOverride: thor-api
  image:
    pullPolicy: Always

bifrost:
  fullnameOverride: bifrost
  image:
    pullPolicy: Always

midgard:
  fullnameOverride: midgard

binance-daemon:
  fullnameOverride: binance-daemon

bitcoin-daemon:
  enabled: false
  fullnameOverride: bitcoin-daemon

ethereum-daemon:
  enabled: false
  fullnameOverride: ethereum-daemon

bepswap:
  enabled: false
  fullnameOverride: bepswap
