thor-daemon:
  fullnameOverride: thor-daemon
  priorityClassName: high-priority

thor-api:
  fullnameOverride: thor-api
  priorityClassName: high-priority
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: "thor-daemon"
        topologyKey: "kubernetes.io/hostname"

bifrost:
  fullnameOverride: bifrost
  priorityClassName: high-priority
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: "thor-daemon"
        topologyKey: "kubernetes.io/hostname"

midgard:
  fullnameOverride: midgard

binance-daemon:
  fullnameOverride: binance-daemon

bitcoin-daemon:
  enabled: false
  fullnameOverride: bitcoin-daemon

ethereum-daemon:
  enabled: false
  fullnameOverride: ethereum-daemon

bepswap:
  enabled: false
  fullnameOverride: bepswap
