apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "bifrost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bifrost.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bifrost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-thorchain
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup thor-api; do echo waiting for thorchain; sleep 2; done"]
      - name: init-bitcoin
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup bitcoin-daemon-rpc; do echo waiting for bitcoin; sleep 2; done"]
      - name: init-binance
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup binance-daemon-rpc; do echo waiting for binance; sleep 2; done"]
      - name: init-ethereum
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup ethereum-daemon-rpc; do echo waiting for ethereum; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/bifrost.sh"]
          args: ["bifrost", "-c", "/etc/bifrost/config.json", "-l", "debug"]
          volumeMounts:
            - mountPath: /var/data/bifrost
              name: data
            {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
          env:
            - name: NET
              value: {{ .Values.net }}
            - name: CHAIN_API
              value: {{ .Values.thorApi }}
            - name: CHAIN_RPC
              value: {{ .Values.thorDaemon }}
            - name: BINANCE_HOST
              value: {{ .Values.binanceDaemon }}
            - name: BTC_HOST
              value: {{ .Values.bitcoinDaemon }}
            - name: ETH_HOST
              value: {{ .Values.ethereumDaemon }}
            - name: PEER
              value: {{ .Values.peer }}
            - name: SIGNER_NAME
              value: {{ .Values.signer.name }}
            - name: SIGNER_PASSWORD
              value: {{ .Values.signer.password }}
            - name: SIGNER_SEED_PHRASE
              value: {{ .Values.signer.mnemonic }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "bifrost.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
