apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - name: prometheus
      port: 26660
      targetPort: prometheus
      protocol: TCP
  selector:
    {{- include "bifrost.selectorLabels" . | nindent 4 }}
