# Default values for telegram-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: mainnet

telegramToken: ""

ethereumDaemon: ethereum-daemon:8545
binanceDaemon:
  testnet: binance-daemon:26657
  mainnet: binance-daemon:27147
bitcoinDaemon:
  testnet: thorchain:password@bitcoin-daemon:18332
  mainnet: thorchain:password@bitcoin-daemon:8332
bitcoinCashDaemon:
  testnet: thorchain:password@bitcoin-cash-daemon:18332
  mainnet: thorchain:password@bitcoin-cash-daemon:8332
litecoinDaemon:
  testnet: thorchain:password@litecoin-daemon:19332
  mainnet: thorchain:password@litecoin-daemon:9332

seed:
  testnet: https://testnet.seed.thorchain.info
  mainnet: https://seed.thorchain.info

allowedUserIds: ALL

replicaCount: 1

image:
  name: block42blockchaincompany/thornode_bot
  tag: "" # When tag is empty it defaults to the chart appVersion.
  hash: e7605c0697672e0f0058903fad49a81a504479d71bba7f499902e5933bb58997

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
  # storageClass: "-"
  # hostPath: /host-path
  # subPath: subpath

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
