apiVersion: v1
kind: Service
metadata:
  name: {{ include "thor-daemon.fullname" . }}
  labels:
    {{- include "thor-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.port.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "thor-daemon.selectorLabels" . | nindent 4 }}
