apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xrp-daemon.fullname" . }}-scripts
data:
  probe.sh: |
    #!/bin/bash

    set -euo pipefail

    FILE=/var/lib/rippled/.probe_last_height

    STATUS=$(rippled --silent ledger_closed | grep "ledger_index" | cut -d':' -f2 | tr -d ' ,') || exit 1
    if [ ! -f "$FILE" ]; then
      echo "$STATUS" >$FILE
      exit 1
    fi

    OLD=$(cat $FILE)
    echo "$STATUS" > $FILE
    CURRENT=$(cat $FILE)
    [ "$OLD" == "$CURRENT" ] && exit 1 || exit 0

  rippled.cfg: |
    [server]
    port_rpc_admin_local
    port_rpc
    port_ws_admin_local
    port_ws_public
    port_peer
    # ssl_key = /etc/ssl/private/server.key
    # ssl_cert = /etc/ssl/certs/server.crt

    [port_rpc_admin_local]
    port = 5005
    ip = 127.0.0.1
    admin = 127.0.0.1
    protocol = http

    [port_ws_admin_local]
    port = 6006
    ip = 127.0.0.1
    admin = 127.0.0.1
    protocol = ws

    [port_ws_public]
    port = 80
    ip = 0.0.0.0
    protocol = ws

    [port_peer]
    port = 51235
    ip = 0.0.0.0
    protocol = peer

    [port_rpc]
    port = 51234
    ip = 0.0.0.0
    admin = 127.0.0.1
    protocol = https, http

    [node_size]
    huge
    # tiny
    # small
    # medium
    # large
    # huge

    [node_db]
    type=NuDB
    path=/var/lib/rippled/db/nudb
    advisory_delete=0

    # How many ledgers do we want to keep (history)?
    # Integer value that defines the number of ledgers
    # between online deletion events
    online_delete=25000

    [ledger_history]
    # How many ledgers do we want to keep (history)?
    # Integer value (ledger count)
    # or (if you have lots of TB SSD storage): 'full'
    #
    #   The number of past ledgers to acquire on server startup and the minimum to
    #   maintain while running.
    #
    #   To serve clients, servers need historical ledger data. Servers that don't
    #   need to serve clients can set this to "none".  Servers that want complete
    #   history can set this to "full".
    #
    #   This must be less than or equal to online_delete (if online_delete is used)
    #
    #   The default is: 256
    #
    25000

    [database_path]
    /var/lib/rippled/db

    [debug_logfile]
    /var/log/rippled/debug.log

    [sntp_servers]
    time.windows.com
    time.apple.com
    time.nist.gov
    pool.ntp.org

    [validators_file]
    validators.txt

    [rpc_startup]
    { "command": "log_level", "severity": "warning" }
    # severity (order: lots of information .. only errors)
    # debug
    # info
    # warn
    # error
    # fatal    

    [ssl_verify]
    1

  validators.txt: |
    [validator_list_sites]
    https://vl.ripple.com
    https://vl.xrplf.org

    [validator_list_keys]
    #vl.ripple.com
    ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734
    # vl.xrplf.org
    ED45D1840EE724BE327ABE9146503D5848EFD5F38B6D5FEDE71E80ACCE5E6E738B
