apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitcoin-daemon.fullname" . }}
  labels:
    {{- include "bitcoin-daemon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bitcoin-daemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bitcoin-daemon.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bitcoin-daemon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-scripts
          image: "{{ .Values.image.scripts.repository }}:{{ .Values.image.scripts.tag }}"
          imagePullPolicy: {{ .Values.image.scripts.pullPolicy }}
          volumeMounts:
            - name: scripts
              mountPath: /tmp
          command: [ "sh", "-c", "cp /scripts/* /tmp" ]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.bitcoin.repository }}:{{ .Values.image.bitcoin.tag }}"
          imagePullPolicy: {{ .Values.image.bitcoin.pullPolicy }}
          command: [ "sh", "-c", "apk add curl && /scripts/bitcoin-mock.sh" ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data
              mountPath: /home/bitcoin/.bitcoin
          ports:
          ports:
            - name: p2p
              containerPort: {{ .Values.service.p2p.port }}
              protocol: TCP
            - name: rpc
              containerPort: {{ .Values.service.rpc.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - -X POST
                - http://localhost:{{ .Values.service.rpc.port }}
          readinessProbe:
            exec:
              command:
                - curl
                - -X POST
                - http://localhost:{{ .Values.service.rpc.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: scripts
        emptyDir: {}
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "bitcoin-daemon.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
