apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-daemon.fullname" . }}-p2p
  labels:
    {{- include "bitcoin-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.p2p.type }}
  ports:
    - port: {{ .Values.service.p2p.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "bitcoin-daemon.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-daemon.fullname" . }}-rpc
  labels:
    {{- include "bitcoin-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rpc.type }}
  ports:
    - port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "bitcoin-daemon.selectorLabels" . | nindent 4 }}
