# Default values for terra-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: mainnet

replicaCount: 1

image:
  name: terramoney/core-node
  pullPolicy: IfNotPresent
  tag: "" # When tag is empty it defaults to the chart appVersion.
  hash: "ba3b6a36f37fd62d5d1e116d8a25e7e5e87ea1bafaf4267e2fc3b896ef973605"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Choose closest mirror for faster sync: https://quicksync.io/networks/terra.html.
# Options at time of writing:
# - SanFrancisco
# - Netherlands
# - Singapore
quicksyncMirror: Netherlands

service:
  type: ClusterIP
  port:
    mainnet:
      p2p: 26656
      rpc: 26657
      grpc: 9090
    stagenet:
      p2p: 26656
      rpc: 26657
      grpc: 9090

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     pathType: ImplementationSpecific
    #     backend:
    #       service
    #         name: gateway
    #         port:
    #           name: midgard
  tls:
    []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 50Gi
    mainnet: 3072Gi
    stagenet: 3072Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  fsGroup: 1000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 4
    memory: 27Gi
  limits:
    # cpu: 2
    memory: 27Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  images:
    alpine:
      tag: latest
      hash: 4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
