# Default values for dogecoin-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

net: mainnet

image:
  name: registry.gitlab.com/thorchain/devops/node-launcher
  tag: "dogecoin-daemon-1.14.8"
  hash: "6f9094ab8f68672292ea9868ab4b2470beee0184059678f6172b19757408b902"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

persistence:
  enabled: true
  size:
    stagenet: 300Gi
    mainnet: 300Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

podSecurityContext:
  fsGroup: 1000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port:
    mainnet:
      p2p: 22556
      rpc: 22555
    stagenet:
      p2p: 22556
      rpc: 22555

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls:
    []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

resources:
  limits:
    # cpu: 1
    memory: 24Gi
  requests:
    cpu: 1
    memory: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}

global: {}
