global:
  tag: mocknet
  net: mocknet
  mnemonicSecret: thornode-mnemonic
  gateway:
    enabled: false
  binanceDaemon: http://binance-daemon.genesis:26657

bifrost:
  peer: bifrost.genesis
  service:
    type: ClusterIP

thornode:
  peer: thornode.genesis
  seeds: thornode.genesis
  peerApi: thornode.genesis
  service:
    type: ClusterIP

gateway:
  enabled: false

binance-daemon:
  enabled: false

midgard:
  enabled: false
  image:
    tag: mocknet
