releases:
  - name: genesis
    chart: ../thornode
    version: 0.1.0
    namespace: genesis
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
        mnemonic: soldier tank ribbon above result process tide avocado enforce twice myself taste arrow stamp trend hub relax tired monster bone inch steel uphold charge
        thor-gateway:
          enabled: false
        bifrost:
          binanceStartBlockHeight: 1

  - name: validator-1
    chart: ../thornode
    version: 0.1.0
    namespace: validator-1
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: infant exchange ripple diet rebuild enact apology erode job throw faculty flight sock october same melt defense cook echo wise tobacco fatal egg nothing
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-2
    chart: ../thornode
    version: 0.1.0
    namespace: validator-2
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: edit tenant confirm word debate ginger urge bus cushion normal surface depend film much interest subway august frozen hobby fatal soon shock life message
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-3
    chart: ../thornode
    version: 0.1.0
    namespace: validator-3
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: noodle deer august stay cradle shrug inform alpha recycle audit tribe pelican payment produce appear region economy annual nut frown sauce much kick warrior
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-4
    chart: ../thornode
    version: 0.1.0
    namespace: validator-4
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: project pride grant dawn soccer couple snap swing laundry until icon weather because obvious clog often huge whisper unit side suit employ borrow reunion
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-5
    chart: ../thornode
    version: 0.1.0
    namespace: validator-5
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: what sell bitter enjoy frozen pizza myth pepper garment chapter drill rural globe please clap sing title enroll ladder siren flock donate liberty remove
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-6
    chart: ../thornode
    version: 0.1.0
    namespace: validator-6
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: original dirt tiny note pledge hint rather code ugly kite rain stamp exile until plate jazz reason nation mom penalty portion glue spring limit
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-7
    chart: ../thornode
    version: 0.1.0
    namespace: validator-7
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: two almost ball rule lawsuit soon chaos ignore concert proud interest find tissue cram skate gospel damage mountain club review shield anger giant diary
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-8
    chart: ../thornode
    version: 0.1.0
    namespace: validator-8
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: service junk alone utility pear profit used draw girl rack car cattle hurdle donkey empty shift setup creek grit volume crime spin silk token
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-9
    chart: ../thornode
    version: 0.1.0
    namespace: validator-9
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: attack payment curious dwarf attack robust purchase trade when report good curtain detail want eagle riot use volume radar lamp spike caution drift mobile
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-10
    chart: ../thornode
    version: 0.1.0
    namespace: validator-10
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: jacket bachelor fine rookie maid shiver title illegal essay afraid enjoy sauce diesel onion turkey crew record fade analyst romance warrior annual blame furnace
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-11
    chart: ../thornode
    version: 0.1.0
    namespace: validator-11
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: project point select blur hospital liar galaxy crucial bottom flush fetch faith grief valid retreat drastic fence pepper ivory advance equip hire shallow marble
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-12
    chart: ../thornode
    version: 0.1.0
    namespace: validator-12
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: emerge transfer spatial electric hint quarter modify matrix bench whip canoe super unveil entry put horse barely canyon poverty quarter police train fuel body
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-13
    chart: ../thornode
    version: 0.1.0
    namespace: validator-13
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: sign beef glue custom slot jelly identify sheriff magnet click index dove inspire long often spice roof run asset position home nest sausage owner
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-14
    chart: ../thornode
    version: 0.1.0
    namespace: validator-14
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: sea outside control burden fog reduce nature festival verb type tumble blind entire glimpse chapter claw bid diet lady focus pen ritual effort limit
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-15
    chart: ../thornode
    version: 0.1.0
    namespace: validator-15
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: blade such habit october danger scare since sister now hurry garden fatal fat animal memory glove volcano start illness express great diary pyramid suffer
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-16
    chart: ../thornode
    version: 0.1.0
    namespace: validator-16
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: fold argue fever away fame motion goose pond dry chair remain barrel ranch unfold forget fade defy crime history pledge disagree loud ten misery
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-17
    chart: ../thornode
    version: 0.1.0
    namespace: validator-17
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: floor naive chase erase company arena manage custom rose vintage cute fork peasant latin fork senior equal domain faith grid quarter stage improve student
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-18
    chart: ../thornode
    version: 0.1.0
    namespace: validator-18
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: sting winter punch floor clinic used alert hurry damp elevator remember retreat absent example rent divorce green wave receive element medal nation myth police
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-19
    chart: ../thornode
    version: 0.1.0
    namespace: validator-19
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: wolf system range dance vendor across address pink vital about remove steel warrior property clean female fish stairs tent silly setup safe chair picnic
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false

  - name: validator-20
    chart: ../thornode
    version: 0.1.0
    namespace: validator-20
    values:
      - global:
          tag: mocknet
          net: mocknet
          mnemonicSecret: thornode-mnemonic
          gateway:
            enabled: false
          binanceDaemon: http://binance-daemon.genesis:26657
        mnemonic: cupboard wrong drive pepper scrub heavy repeat expire volume legend border poet shell fancy devote crowd crucial section actual connect sure stay honey feature
        bifrost:
          peer: bifrost.genesis
        thor-daemon:
          peer: thor-daemon.genesis
          peerApi: thor-api.genesis
        thor-gateway:
          enabled: false
        binance-daemon:
          enabled: false
